import type { LookEmailOnIcyPeasOptions, LookEmailOnIcyPeasResult } from '../icypeasActivities';

interface Dependencies {
  request: (body: Record<string, string>, timeout: number) => Promise<{
    success: boolean; data?: any; error?: { message?: string; code?: string; status?: number; retryAfterMs?: number };
  }>;
  sleep: (ms: number) => Promise<void>;
  now: () => number;
  signal?: AbortSignal;
}

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const EMAIL = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const MAX_WAIT_MS = 240_000; // Finish before the activity's five-minute timeout.

/** The API durably creates once and then reads the same search across retries/runs. */
export async function resolveIcyPeasEmail(options: LookEmailOnIcyPeasOptions, deps: Dependencies): Promise<LookEmailOnIcyPeasResult> {
  if ([options.firstname, options.lastname, options.domainOrCompany].some(value => value !== undefined && typeof value !== 'string')) {
    return { success: false, outcome: 'failed', error: 'Invalid IcyPeas search fields' };
  }
  const firstname = options.firstname?.trim() || '';
  const lastname = options.lastname?.trim() || '';
  const domainOrCompany = options.domainOrCompany?.trim();
  if (!options.site_id || !UUID.test(options.site_id)) {
    return { success: false, outcome: 'failed', error: 'IcyPeas durable lookup requires site_id; restart legacy executions with the updated workflow' };
  }
  if (!domainOrCompany || (!firstname && !lastname)) {
    return { success: false, outcome: 'failed', error: 'IcyPeas requires a domain/company and a first or last name' };
  }
  // Provider custom IDs are generated by the durable API, never by a caller.
  const body = { site_id: options.site_id, firstname, lastname, domainOrCompany };
  const deadline = deps.now() + MAX_WAIT_MS;
  let searchId: string | undefined;
  const failed = (error: string, outcome: 'failed' | 'pending' = 'failed'): LookEmailOnIcyPeasResult => ({
    success: false, outcome, searchId, error,
  });
  const waitForNextRead = async (hint: unknown) => {
    const wait = Math.max(15_000, typeof hint === 'number' && Number.isFinite(hint) && hint > 0 ? hint : 15_000);
    if (deps.now() + wait + 1000 >= deadline) return false;
    await deps.sleep(wait);
    return true;
  };
  try {
    while (deps.now() < deadline) {
      deps.signal?.throwIfAborted();
      const response = await deps.request(body, Math.min(20_000, deadline - deps.now()));
      deps.signal?.throwIfAborted();
      if (!response.success) {
        // This endpoint is itself durable/idempotent, unlike the old submit-only
        // route: retrying it after a transport failure cannot start a second job.
        const retryable = response.error?.status === 429 || (response.error?.status ?? 0) >= 500
          || ['NETWORK_ERROR', 'TIMEOUT'].includes(response.error?.code || '');
        if (retryable) {
          if (!await waitForNextRead(response.error?.retryAfterMs ?? 60_000)) break;
          continue;
        }
        return failed(response.error?.message || 'IcyPeas lookup unavailable');
      }
      const result = response.data;
      if (!result || typeof result !== 'object' || typeof result.status !== 'string') {
        return failed('Invalid IcyPeas resolver response');
      }
      if (result.searchId !== undefined) {
        if (typeof result.searchId !== 'string' || !result.searchId.trim() || result.searchId.length > 200
          || (searchId && searchId !== result.searchId)) return failed('IcyPeas search identity changed or is invalid');
        searchId = result.searchId;
      }
      if (result.outcome === 'no_match') {
        if (!searchId || !['NOT_FOUND', 'DEBITED_NOT_FOUND'].includes(result.status)) {
          return failed('IcyPeas no-match was not confirmed by a terminal search');
        }
        return { success: true, outcome: 'no_match', searchId };
      }
      if (result.outcome === 'matched') {
        if (!searchId || !['FOUND', 'DEBITED'].includes(result.status)) return failed('IcyPeas result is not complete');
        if (!Array.isArray(result.emails) || result.emails.length === 0 || result.emails.length > 100) {
          return failed('IcyPeas completed without usable result data');
        }
        const emails = result.emails.filter((value: any) => typeof value?.email === 'string'
          && value.email.length <= 320 && EMAIL.test(value.email)
          && !['undeliverable', 'not_found'].includes(value.certainty))
          .map((value: any) => ({ email: value.email, ...(typeof value.certainty === 'string' ? { certainty: value.certainty } : {}) }));
        if (!emails.length) return failed('IcyPeas completed without usable email addresses');
        // Keep certainty as provider metadata. It is NOT a validation bypass.
        return { success: true, outcome: 'matched', searchId,
          data: { email: emails[0].email, emails, status: result.status } };
      }
      if (result.outcome === 'failed') return failed(typeof result.error === 'string' ? result.error : `IcyPeas failed: ${result.status}`);
      if (result.outcome !== 'pending') return failed('Unknown IcyPeas resolver outcome');
      if (!await waitForNextRead(result.retryAfterMs)) break;
    }
    return failed('IcyPeas search is still pending; its durable ID will be reused on the next execution', 'pending');
  } catch (error) {
    // Cancellation must not become a normal result that triggers more paid fallbacks.
    deps.signal?.throwIfAborted();
    return failed(error instanceof Error ? error.message : 'IcyPeas lookup failed');
  }
}